/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Pronosticator.java
 *
 * Created on 28-may-2010, 15:20:40
 */

package pronosticator;

/*
 *
 * @author albertolagos
 */
public class Pronosticator extends javax.swing.JPanel {
    private Ciudad ciudades;
    private URLConnectionReader conexion;
    private Configuracion conf;
    /** Creates new form Pronosticator */
    public Pronosticator() {
        super();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaDeCiudades = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();

        setName("Form"); // NOI18N

        listaDeCiudades.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaDeCiudades.setName("listaDeCiudades"); // NOI18N
        listaDeCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaDeCiudadesActionPerformed(evt);
            }
        });

        jSeparator2.setComponentOrientation(null);
        jSeparator2.setName("jSeparator2"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(264, 264, 264)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
            .add(listaDeCiudades, 0, 361, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .add(listaDeCiudades, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(89, 89, 89))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listaDeCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaDeCiudadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaDeCiudadesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox listaDeCiudades;
    // End of variables declaration//GEN-END:variables

}
