package pronosticator;

import java.util.LinkedList;
import javax.swing.ImageIcon;

/**
 * Clase Principal que implementa el widget (JPanel).
 * 
 * @author Alberto Lagos T.
 */

public class Pronosticator extends javax.swing.JPanel {
    
    private LinkedList<Ciudad> ciudades;
    private Parser datos;
    private Configuracion conf;
    /** Creates new form Pronosticator */
    public Pronosticator() {
        super();
        initComponents();
        ejecutar();
    }
    public void ejecutar() {
        datos = new Parser("http://www.meteochile.cl/js/pronostico_general.js");
        Ciudad c[] = datos.generarCiudades();
        ciudades = new LinkedList();
        for(int i = 0;i<c.length-1;i++) {
            ciudades.addLast(c[i]);
            listaDeCiudades.addItem((ciudades.get(i)).obtenerNombre());
        }
        
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        listaDeCiudades = new javax.swing.JComboBox();
        tempMaxD3 = new javax.swing.JLabel();
        iconoD3 = new javax.swing.JLabel();
        tempMaxD2 = new javax.swing.JLabel();
        iconoD2 = new javax.swing.JLabel();
        tempMaxD1 = new javax.swing.JLabel();
        iconoD1 = new javax.swing.JLabel();
        tempMaxD4 = new javax.swing.JLabel();
        iconoD4 = new javax.swing.JLabel();
        fechaD2 = new javax.swing.JLabel();
        fechaD3 = new javax.swing.JLabel();
        fechaD4 = new javax.swing.JLabel();
        fechaD1 = new javax.swing.JLabel();
        pronosticoD4 = new javax.swing.JLabel();
        pronosticoD1 = new javax.swing.JLabel();
        pronosticoD2 = new javax.swing.JLabel();
        pronosticoD3 = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(380, 269));
        setLayout(null);

        jSeparator2.setName("jSeparator2"); // NOI18N
        add(jSeparator2);
        jSeparator2.setBounds(264, 255, 0, 12);

        jSeparator1.setName("jSeparator1"); // NOI18N
        add(jSeparator1);
        jSeparator1.setBounds(0, 140, 480, 12);

        jSeparator3.setName("jSeparator3"); // NOI18N
        add(jSeparator3);
        jSeparator3.setBounds(80, 180, 0, 30);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setName("jSeparator4"); // NOI18N
        add(jSeparator4);
        jSeparator4.setBounds(140, 140, 12, 160);

        jSeparator5.setName("jSeparator5"); // NOI18N
        add(jSeparator5);
        jSeparator5.setBounds(190, 200, 0, 12);

        jSeparator6.setName("jSeparator6"); // NOI18N
        add(jSeparator6);
        jSeparator6.setBounds(190, 190, 0, 12);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator7.setName("jSeparator7"); // NOI18N
        add(jSeparator7);
        jSeparator7.setBounds(310, 140, 10, 160);

        listaDeCiudades.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Ciudad" }));
        listaDeCiudades.setName("listaDeCiudades"); // NOI18N
        listaDeCiudades.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaDeCiudadesItemStateChanged(evt);
            }
        });
        add(listaDeCiudades);
        listaDeCiudades.setBounds(10, 10, 190, 27);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pronosticator.PronosticatorApp.class).getContext().getResourceMap(Pronosticator.class);
        tempMaxD3.setFont(resourceMap.getFont("tempMaxD3.font")); // NOI18N
        tempMaxD3.setText(resourceMap.getString("tempMaxD3.text")); // NOI18N
        tempMaxD3.setName("tempMaxD3"); // NOI18N
        add(tempMaxD3);
        tempMaxD3.setBounds(210, 130, 100, 60);

        iconoD3.setText(resourceMap.getString("iconoD3.text")); // NOI18N
        iconoD3.setName("iconoD3"); // NOI18N
        add(iconoD3);
        iconoD3.setBounds(160, 150, 128, 128);

        tempMaxD2.setFont(resourceMap.getFont("tempMaxD2.font")); // NOI18N
        tempMaxD2.setText(resourceMap.getString("tempMaxD2.text")); // NOI18N
        tempMaxD2.setName("tempMaxD2"); // NOI18N
        add(tempMaxD2);
        tempMaxD2.setBounds(40, 130, 110, 60);

        iconoD2.setText(resourceMap.getString("iconoD2.text")); // NOI18N
        iconoD2.setName("iconoD2"); // NOI18N
        add(iconoD2);
        iconoD2.setBounds(10, 150, 128, 128);

        tempMaxD1.setFont(resourceMap.getFont("tempMaxD1.font")); // NOI18N
        tempMaxD1.setText(resourceMap.getString("tempMaxD1.text")); // NOI18N
        tempMaxD1.setName("tempMaxD1"); // NOI18N
        add(tempMaxD1);
        tempMaxD1.setBounds(370, 0, 110, 70);

        iconoD1.setText(resourceMap.getString("iconoD1.text")); // NOI18N
        iconoD1.setName("iconoD1"); // NOI18N
        add(iconoD1);
        iconoD1.setBounds(350, 10, 128, 128);

        tempMaxD4.setFont(resourceMap.getFont("tempMaxD4.font")); // NOI18N
        tempMaxD4.setText(resourceMap.getString("tempMaxD4.text")); // NOI18N
        tempMaxD4.setName("tempMaxD4"); // NOI18N
        add(tempMaxD4);
        tempMaxD4.setBounds(380, 130, 100, 60);

        iconoD4.setText(resourceMap.getString("iconoD4.text")); // NOI18N
        iconoD4.setName("iconoD4"); // NOI18N
        add(iconoD4);
        iconoD4.setBounds(330, 150, 128, 128);

        fechaD2.setText(resourceMap.getString("fechaD2.text")); // NOI18N
        fechaD2.setName("fechaD2"); // NOI18N
        add(fechaD2);
        fechaD2.setBounds(10, 230, 120, 16);

        fechaD3.setText(resourceMap.getString("fechaD3.text")); // NOI18N
        fechaD3.setName("fechaD3"); // NOI18N
        add(fechaD3);
        fechaD3.setBounds(210, 220, 100, 16);

        fechaD4.setText(resourceMap.getString("fechaD4.text")); // NOI18N
        fechaD4.setName("fechaD4"); // NOI18N
        add(fechaD4);
        fechaD4.setBounds(330, 220, 150, 16);

        fechaD1.setText(resourceMap.getString("fechaD1.text")); // NOI18N
        fechaD1.setName("fechaD1"); // NOI18N
        add(fechaD1);
        fechaD1.setBounds(340, 120, 140, 16);

        pronosticoD4.setText(resourceMap.getString("pronosticoD4.text")); // NOI18N
        pronosticoD4.setName("pronosticoD4"); // NOI18N
        add(pronosticoD4);
        pronosticoD4.setBounds(330, 240, 150, 16);

        pronosticoD1.setText(resourceMap.getString("pronosticoD1.text")); // NOI18N
        pronosticoD1.setName("pronosticoD1"); // NOI18N
        add(pronosticoD1);
        pronosticoD1.setBounds(10, 60, 230, 16);

        pronosticoD2.setText(resourceMap.getString("pronosticoD2.text")); // NOI18N
        pronosticoD2.setName("pronosticoD2"); // NOI18N
        add(pronosticoD2);
        pronosticoD2.setBounds(10, 240, 140, 50);

        pronosticoD3.setText(resourceMap.getString("pronosticoD3.text")); // NOI18N
        pronosticoD3.setName("pronosticoD3"); // NOI18N
        add(pronosticoD3);
        pronosticoD3.setBounds(210, 240, 100, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void listaDeCiudadesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaDeCiudadesItemStateChanged
        // TODO add your handling code here:
        System.out.println(listaDeCiudades.getSelectedIndex());
        Ciudad tmp = ciudades.get(listaDeCiudades.getSelectedIndex());

        /* Obteniendo temperaturas */

        tempMaxD1.setText(""+tmp.obtenerPronostico().obtenerTemperaturaMax()[0]+"º");
        tempMaxD2.setText(""+tmp.obtenerPronostico().obtenerTemperaturaMax()[1]+"º");
        tempMaxD3.setText(""+tmp.obtenerPronostico().obtenerTemperaturaMax()[2]+"º");
        tempMaxD4.setText(""+tmp.obtenerPronostico().obtenerTemperaturaMax()[3]+"º");

        /* Obteniendo fechas */

        fechaD1.setText(tmp.obtenerPronostico().obtenerFecha()[0]);
        fechaD2.setText(tmp.obtenerPronostico().obtenerFecha()[1]);
        fechaD3.setText(tmp.obtenerPronostico().obtenerFecha()[2]);
        fechaD4.setText(tmp.obtenerPronostico().obtenerFecha()[3]);

        /* Obteniendo Iconos */
        ImageIcon ic;
//        if(tmp.obtenerPronostico().obtenerIconos()[1] == "")
        iconoD2.setDisabledIcon(new ImageIcon(getClass().getResource("tiempoicons/00.png")));
        iconoD2.setEnabled(false);

        /* Obteniendo los pronosticos en palabras */
        
        pronosticoD1.setText(tmp.obtenerPronostico().obtenerPronostico()[0]);
    }//GEN-LAST:event_listaDeCiudadesItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fechaD1;
    private javax.swing.JLabel fechaD2;
    private javax.swing.JLabel fechaD3;
    private javax.swing.JLabel fechaD4;
    private javax.swing.JLabel iconoD1;
    private javax.swing.JLabel iconoD2;
    private javax.swing.JLabel iconoD3;
    private javax.swing.JLabel iconoD4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JComboBox listaDeCiudades;
    private javax.swing.JLabel pronosticoD1;
    private javax.swing.JLabel pronosticoD2;
    private javax.swing.JLabel pronosticoD3;
    private javax.swing.JLabel pronosticoD4;
    private javax.swing.JLabel tempMaxD1;
    private javax.swing.JLabel tempMaxD2;
    private javax.swing.JLabel tempMaxD3;
    private javax.swing.JLabel tempMaxD4;
    // End of variables declaration//GEN-END:variables

}
